//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasarimDesenleri_odev1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResimYolu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResimYolu()
        {
            this.DosyalamaArsivleme = new HashSet<DosyalamaArsivleme>();
            this.HesapMakinesi = new HashSet<HesapMakinesi>();
            this.KagitUrunleri = new HashSet<KagitUrunleri>();
            this.Mikroskop = new HashSet<Mikroskop>();
            this.OkulCantalari = new HashSet<OkulCantalari>();
            this.OkulDefterleri = new HashSet<OkulDefterleri>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DosyalamaArsivleme> DosyalamaArsivleme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HesapMakinesi> HesapMakinesi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KagitUrunleri> KagitUrunleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mikroskop> Mikroskop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OkulCantalari> OkulCantalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OkulDefterleri> OkulDefterleri { get; set; }
    }
}
